### ISSUE TITLE
Aplikasi crash saat pertama kali install

### ISSUE THREAD

**Issue by JollyFrankle** [Dietin/Mobile-Development#1]
**Description:**
Saat pertama kali menginstall aplikasi di emulator, aplikasi tidak mengalami _crash_ (_force stop_), tetapi ketika menginstall aplikasi di _physical device_ (HP), aplikasi dapat dibuka selama beberapa detik tetapi kemudian mengalami _crash_ (_force stop_).

**Steps to reproduce:**
1. Open Android Studio project
2. Run on emulator
3. Verify if the app can execute successfully
4. Run on physical device
5. The app will force close after a few seconds

**Expected behaviour:**
Aplikasi akan terbuka dan memuat data ke dalam TextView yang sudah disediakan

**Actual behaviour:**
Aplikasi memanggil function onDestroyView sebelum memuat data ke TextView yang sudah disediakan.

**Environment details:**
- Emulator:
  - Google Pixel 6
  - API version 26 (Android 8.0)
- Physical device
  - Samsung Galaxy A33 5G
  - API version 33 (Android 13)
  - OneUI version 5.1

**Screenshots or code snippets:**
![image](https://github.com/JollyFrankle/DietinAndroidApp/assets/64875622/e6c4fb22-37c6-4407-8991-96e46383a439)
Setelah menambahkan Log pada onDestroyView, kita mengetahui bahwa onDestroyView sudah dipanggil terlebih dahulu sebelum data dimuat

**Possible solution:**
- Delete bagian code `_binding = null` pada onDestroyView, [tapi nanti memory leak](https://developer.android.com/topic/libraries/view-binding#fragments)

**Comment by Vincent-SJ01** [comment]
coba comment line 42... 
`thisIsNotAGoodArchitecturePleaseMoveToViewModelWithLiveDataButJustForTestingThisIsOkayHere()`

kemungkinan pengaruhnya di sana...

**Comment by JollyFrankle** [comment]
Oke, jadi barusan mencoba meng-comment function itu, nah tidak crash lagi, tetapi onDestroyView nya masih tetap dipanggil, jadi saat di-run, keliatannya seperti "flashing" (sempat muncul fragmentnya, kemudian hilang, kemudian muncul lagi.

![image](https://github.com/JollyFrankle/DietinAndroidApp/assets/64875622/4c32199e-023a-4ad1-a963-2638a5723605)

Tapi kalau begini ya datanya tidak akan ditampilkan....

**Comment by Vincent-SJ01** [comment]
mungkin berkaitan dengan navigation.. jadi fragment dibuat dan destroy lagi... 
yaudah tapi gpp.. kan itu testing.. jadi ga dipake jugaaa.. :))))) 

ganti ke metode tradisional ajaaa... :"))

**Comment by JollyFrankle** [comment]
Hmm...... iya sih testing juga ya
Yaudah lah skip aja yg ini :)
